apiVersion: v1
kind: Service
metadata:
  name: model-server
  labels:
    app.kubernetes.io/name: umodel
    app.kubernetes.io/component: server
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: umodel
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30080
